const ALERTS = "ALERTS";

const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export { ALERTS, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT };
